jobs:
- name: test-stargate
  serial: true
  plan:
  - get: stargate-develop
  - task: test
    file: stargate-develop/ci/tasks/test/task-test.yml
    input_mapping:
      stargate: stargate-develop


resources:
- name: stargate-develop
  type: git
  source:
    uri: git@github.com:mikemimik/stargate.git
    branch: develop
    private_key: ((repository-private-key))

- name: stargate-master
  type: git
  source:
    uri: git@github.com:mikemimik/stargate.git
    branch: master
    private_key: ((repository-private-key))

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
